# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa761ac333ebf82e101c6e3fc7c1433b747479623361a7957003ed4140c8169d93e4e98adcef68a339e0f2c60c14da077ce704af14c14b8a976810a40b58293

test:
  secret_key_base: 9e5c734fddaba0fc9af8c50a5052f4b7e15e0deb5b1e2ab79277658612e7f2954a6a8c6befb08adfa951d8d9f630e2d09fe4b871e5253b811e278349349bb9c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
